server {
    listen 80;
    server_name odysseus.xedoc.ru;

    root /var/www/odysseus.xedoc.ru/dist;
    index index.html;

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
